import type { Metadata } from 'next';
import { ThemeProvider } from '@/components/custom/theme-provider';
import { Toaster } from '@/components/ui/toaster';
import { WEBSITE } from '@/constants';
import { cn } from '@/lib/utils';
import Console from '@/components/custom/console';
import '@/styles/globals.css';
import { SessionProvider } from 'next-auth/react';
import { StoreProvider } from '@/components/custom/store-provider';
import { auth } from '@/lib/auth';

export const metadata: Metadata = {
    title: {
        template: `%s - ${WEBSITE}`,
        default: WEBSITE
    },
    description: 'Generated by create qnets app'
};

export default async function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await auth();

    return (
        <html lang="zh-CN" suppressHydrationWarning>
            <body className={cn('overflow-x-clip scroll-smooth')}>
                <SessionProvider>
                    <StoreProvider
                        user={{
                            id: session?.user?.id || '',
                            name: session?.user?.name || '',
                            email: session?.user?.email || '',
                            image: session?.user?.image || ''
                        }}
                    >
                        <ThemeProvider
                            attribute="class"
                            defaultTheme="system"
                            storageKey="qnets-ui-theme"
                            enableSystem
                            disableTransitionOnChange
                        >
                            {children}
                            <Console />
                            <Toaster />
                        </ThemeProvider>
                    </StoreProvider>
                </SessionProvider>
            </body>
        </html>
    );
}
